spring:
  application:
    name: hotel
  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot: DEBUG


#spring:
#  datasource:
#  url: jdbc:h2:mem:testdb
#  driverClassName: org.h2.Driver
#  username: sa
#  password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true
